name: messenger_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.4
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  firebase_messaging: ^14.7.15
  firebase_storage: ^11.6.5
  image_picker: ^1.0.7
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
